add parcel data
geomarker-io/codec pull request #105
Opened 2024-08-20 19:54 UTC by erikarasnick

2024-08-21 13:09 UTC, cole-brokamp requested changes

2024-08-21 13:09 UTC, cole-brokamp commented on inst/codec_data/parcel/parcel.R
> +  tibble::as_tibble() |>
with the newer version of dpkg, converting to tibble before using dplyr shouldn't be needed; I just wanted to make sure it was working as expected...

2024-08-21 13:09 UTC, cole-brokamp commented on inst/codec_data/parcel/README.md
> +Parcel-level measures of market total value, acreage, year built, and number of rooms were summarized at the tract level using the median. Because not all parcels in a tract have housing violations,
I think this would be clearer as bullet points.

2024-08-21 13:09 UTC, cole-brokamp commented on inst/codec_data/parcel/README.md
> +
Add what versions of each package this uses?

Version 0.1.0 of the `parcel` CoDEC data resource harmonizes `cagis_parcels-v1.1.0`, `auditor_online_parcels-v0.2.0`, and `property_code_enforcements-v1.0.0`.

2024-08-21 13:09 UTC, cole-brokamp commented on inst/codec_data/parcel/parcel.R
> +      land_use %in% c("apartment, 40+ units", "apartment, 4-19 units", "office / apartment over", "apartment, 20-39 units") ~ "apartment",
add this to readme

- apartment: `apartment, 40+ units`, `apartment, 4-19 units`, `office / apartment over`, ....
- single_family_dwelling: `single family dwelling`

and so on...

2024-08-26 16:38 UTC, erikarasnick commented
decide if we want to release to s3 or gh releases?

2024-09-04 01:58 UTC, merged